Create Animals Table
sunga12/Vet-clinic-database pull request #1
Opened 2023-07-20 00:46 UTC by sunga12

1. Created a database named vet_clinic.
2. Created a table named animals with the given columns:
3. Inserted the given data
4. Wrote queries for the following quests:

- animals whose name ends in "mon".
- name of all animals born between 2016 and 2019.
- name of all animals that are neutered and have less than 3 escape attempts.
- date of birth of all animals named either "Agumon" or "Pikachu".
- name and escape attempts of animals that weigh more than 10.5kg
- animals that are neutered.
- animals not named Gabumon.
- animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)

2023-07-20 00:48 UTC, sunga12 commented
Here are the screenshots of the queries:

![animal table screenshot 1](https://github.com/sunga12/Vet-clinic-database/assets/117270680/bf4cbe18-5637-4407-9623-d385979bf00d)

![animal table screenshot 2](https://github.com/sunga12/Vet-clinic-database/assets/117270680/b043965a-65bf-4db3-9013-7fb525aabdcc)

2023-07-20 00:59 UTC, addod19 requested changes
## Hi @sunga12, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] Schema has the right columns :rocket: 
- [ ] Screenshots of the query results present in the PR :rocket: 


## Required Changes ♻️
_Check the comments under the review._
- [ ] Although you have used the correct README template and which contains all the relevant headers, we are required to customize it according to the current project. Kindly take your time and edit all the sections or headers of the README file before submitting another code review request

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 00:59 UTC, addod19 commented on schema.sql
> +	neutered BOOL,
- [ ] It would be better if we replace `BOOL` with `boolean` instead for the data type

2023-07-20 01:04 UTC, Rustamxon7 approved these changes
Hi @sunga12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯
3. Well-implemented code 👍 

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 01:05 UTC, merged

2023-08-14 07:49 UTC, addod19 reviewed
## Hi @sunga12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] All requirements has been met :rocket: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._